server:
  port: 8090

spring:
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        # 连接池中的最大空闲时间
        max-idle: 20
        # 连接池最大连接数（使用负值表示没限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没限制）
        max-wait: 5000ms
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

# 主数据源配置信息
primary:
  datasource:
    #druid相关配置
    druid:
      driverClassName: org.postgresql.Driver
      password: postgres
      url: jdbc:postgresql://10.0.0.93:50012/postgres
      username: postgres
      #配置初始化大小/最小/最大
      initialSize: 1
      minIdle: 1
      maxActive: 200
      #获取连接等待超时时间
      maxWait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      timeBetweenEvictionRunsMillis: 60000
      #一个连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #打开PSCache，并指定每个连接上PSCache的大小。PSCache对支持游标的数据库性能提升巨大，比如说oracle
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
# 副数据源配置信息
second:
  datasource:
    druid:
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      password: 123123
      url: jdbc:sqlserver://10.0.0.65:1435;DatabaseName=scm_main_gaojiao
      username: sa
      #配置初始化大小/最小/最大
      initialSize: 1
      minIdle: 1
      maxActive: 200
      #获取连接等待超时时间
      maxWait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      timeBetweenEvictionRunsMillis: 60000
      #一个连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #打开PSCache，并指定每个连接上PSCache的大小。PSCache对支持游标的数据库性能提升巨大，比如说oracle
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20

weds:
  thread:
    core-pool-size: 20
    maximum-pool-size: 20
    # 定时任务规划
  timed:
    # 设备状态定时任务规划
    task-state: '0/5 * * * * ?'
    # 设备信息定时任务规划
    task-info: '0 0/10 * * * ?'
  sign:
    # 是否开启接口签名校验
    check: false
    # 拦截器过滤路径
    path-patterns:
      - "/base/**"
      - "/config/**"
      - "/mode/**"
      - "/deviceRecord/**"




